id = "zedrizon-theme"
name = "Zedrizon | Horizon Theme"
version = "0.1.0"
schema_version = 1
authors = ["0xnoid <contact@loatrum.com>"]
description = "A port of jolaleye's Horizon (VSCode) to Zed. Now with extra blur!"
repository = "https://github.com/loatrum/zed_theme.Zedrizon"
